---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Cloud computing

The goal of this series is to help you get started with cloud computing.

At the end of this series you will be able to do things like these:

* Understand what cloud computing is and its benefits.
* Create a server with the tools you need.
* Run RStudio Server on the cloud.
* Scale up and down your computing resources.
* Access shared data on the cloud.
* Run a long process unattended.

## Who is the audience?

Anyone who might benefit from cloud computing, including organizations,
researchers, developers, and interns.

## Why is this important?

Although computing can make our work cheaper and more efficient, we
don't use it because we don't know it well enough.

## Syllabus

### Introduction to cloud computing 

This meetup introduces cloud computing.

Objectives:

* Understand what cloud computing is and its benefits.
* Create a server (droplet) on a cloud (DigitalOcean).
* Explore your server from the console.
* Run RStudio Server. 

### Use cases

This meetup presents three use cases:

1. Scale your computing resources up and down.
2. Run RStudio with useful packages pre-installed.
3. Run long processes unattended.
4. Use case: Publish/access shiny apps.

### Manage data

This meetup helps you manage data.

Objectives:

* Increase disk space to store more data.
* Share data across team members with pins.

### Move data

This meetup covers moving small and bigger data between a server and GitHub
using the `gh` CLI.

Objectives:

* Setup the `gh` CLI.
* Move small data as usual with Git commits.
* Move larger data as assets attached to GitHub releases.

### Next (TBC)

More ways to move data around:

* Move data between a droplet and a container with bind mount volumes.
* Move data between multiple containers with named volumes managed by Docker.
* Move data between a droplet and your computer with `scp`.

## Resources

* YouTube [playlist](https://bit.ly/ds-incubator-videos).
* The
[ds-incubator](https://github.com/2DegreesInvesting/ds-incubator#ds-incubator)
project.
* [Ideas](https://bit.ly/dsi-ideas) for future meetups.
* [An introduction to cloud computing](https://www.digitalocean.com/community/tutorials/a-general-introduction-to-cloud-computing).
* [Take a short, interactive tour of Digital Ocean](https://www.digitalocean.com/try/developer-brand#tour).
